/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Wild9)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8005F7C8u
#define func_8005F7C8 BootEntry  /* alias */
