#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.parse
import urllib.request

SCHEMA = 1
MANIFEST_NAME = "generated-bundle.json"
GEN_MARKER = "generated/SLUS_004.25_dispatch.c"
MAX_BUNDLE_BYTES = 512 * 1024 * 1024


class StripAuthOnHostChange(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        new = super().redirect_request(req, fp, code, msg, headers, newurl)
        if new is None:
            return None
        if _host(newurl) != _host(req.full_url):
            new.headers = {k: v for k, v in new.headers.items()
                           if k.lower() != "authorization"}
        return new


def _host(url: str) -> str:
    return urllib.parse.urlsplit(url).netloc.lower()


def download(url: str, destination: pathlib.Path, token: str | None) -> None:
    headers = {"User-Agent": "wild9recomp-ci/1"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    opener = urllib.request.build_opener(StripAuthOnHostChange())
    written = 0
    with opener.open(request, timeout=300) as response, destination.open("wb") as handle:
        while True:
            chunk = response.read(1 << 20)
            if not chunk:
                break
            written += len(chunk)
            if written > MAX_BUNDLE_BYTES:
                raise ValueError(
                    f"bundle exceeds the {MAX_BUNDLE_BYTES // (1024 * 1024)} MB cap"
                )
            handle.write(chunk)
    if written == 0:
        raise ValueError("downloaded zero bytes")


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text_file(path: pathlib.Path) -> str:
    content = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(content).hexdigest()


def psxrecomp_sha(root: pathlib.Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(root / "psxrecomp"), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.stdout.strip()


def fail(message: str) -> None:
    print(f"  FAIL: {message}", file=sys.stderr)


def verify(
    manifest: dict, root: pathlib.Path, tmp: pathlib.Path, archive: pathlib.Path
) -> pathlib.Path | None:
    if manifest.get("schema") != SCHEMA:
        fail(f"manifest schema {manifest.get('schema')!r}, expected {SCHEMA}")
        return None

    expected_sha = psxrecomp_sha(root)
    actual_sha = manifest.get("psxrecomp_sha")
    if expected_sha is None:
        fail("cannot read the psxrecomp revision; refusing an unpinned bundle")
        print("        generated/ carries no generator version of its own, so this pin"
              " is the only staleness check there is.", file=sys.stderr)
        return None
    if actual_sha != expected_sha:
        fail("the bundle was generated by a different psxrecomp revision")
        print(f"        bundle:  {actual_sha}", file=sys.stderr)
        print(f"        checkout: {expected_sha}", file=sys.stderr)
        print("", file=sys.stderr)
        print(
            "        Regenerate and re-pack:\n"
            "          python3 psxrecomp/psxrecomp_cli.py generate --config game.toml \\\n"
            "              --project-root . --disc '<your Wild 9 .cue>'\n"
            "          scripts/pack_generated_bundle.py",
            file=sys.stderr,
        )
        return None

    expected_toml = sha256_text_file(root / "game.toml")
    raw_toml = sha256_file(root / "game.toml")
    actual_bundle_toml = manifest.get("game_toml_sha256")
    if actual_bundle_toml != expected_toml and actual_bundle_toml != raw_toml:
        fail("game.toml has changed since the bundle was packed")
        print(f"        bundle:   {actual_bundle_toml}", file=sys.stderr)
        print(f"        checkout: {expected_toml}", file=sys.stderr)
        return None

    identity_path = root / "catalog_identity.json"
    if not identity_path.is_file():
        fail(f"{identity_path.name} is missing; the disc fingerprint cannot be checked")
        return None
    rom = json.loads(identity_path.read_text())["rom_identity"]
    if manifest.get("disc_sha1") != rom["data_track"]["sha1"]:
        fail("the bundle was generated from a different disc")
        return None

    staging = tmp / "unpack"
    try:
        with tarfile.open(archive, "r:gz") as tar:
            staging_root = staging.resolve()
            for member in tar.getmembers():
                name = member.name
                if name.startswith("/") or os.path.isabs(name):
                    fail(f"archive member has an absolute path: {name}")
                    return None
                if member.issym() or member.islnk():
                    fail(f"archive member is a link, which extraction would follow: {name}")
                    return None
                target = (staging / name).resolve()
                if target != staging_root and staging_root not in target.parents:
                    fail(f"archive member escapes the target directory: {name}")
                    return None
            tar.extractall(staging)
    except tarfile.TarError as exc:
        fail(f"could not read the archive: {exc}")
        return None

    files: dict[str, str] = manifest.get("files") or {}
    if not files:
        fail("manifest lists no files")
        return None

    for rel, want in sorted(files.items()):
        path = staging / rel
        if not path.is_file():
            fail(f"manifest lists {rel} but the archive does not contain it")
            return None
        got = sha256_file(path)
        if got != want:
            fail(f"{rel} does not match the manifest digest")
            print(f"        got  {got}", file=sys.stderr)
            print(f"        want {want}", file=sys.stderr)
            print("        The upload is probably truncated.", file=sys.stderr)
            return None

    if GEN_MARKER not in files:
        fail(f"manifest has no {GEN_MARKER}")
        print("        That is the GEN_MARKER CMakeLists.txt keys on.", file=sys.stderr)
        return None

    on_disk = {
        p.relative_to(staging).as_posix()
        for p in staging.rglob("*")
        if p.is_file() and p.name != MANIFEST_NAME
    }
    extra = on_disk - set(files)
    missing = set(files) - on_disk
    if extra:
        fail(f"archive has files the manifest does not describe: {sorted(extra)[:5]}")
        return None
    if missing:
        fail(f"manifest describes files the archive lacks: {sorted(missing)[:5]}")
        return None

    total = sum(p.stat().st_size for p in staging.rglob("*") if p.is_file())
    print(
        f"  bundle verified: {len(files)} file(s), {total / 1e6:.1f} MB, "
        f"psxrecomp {actual_sha[:12] if actual_sha else '?'}"
    )
    return staging


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Fetch, verify, and unpack the generated/ bundle."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="re-fetch even if generated/ is already populated",
    )
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    generated = root / "generated"
    marker = root / GEN_MARKER

    if marker.is_file() and not args.force:
        print(f"  {GEN_MARKER} already present; skipping fetch (use --force to override)")
        return 0

    url = os.environ.get("PSXRECOMP_GENERATED_BUNDLE_URL", "").strip()
    if not url:
        print(
            "fetch_generated_bundle: PSXRECOMP_GENERATED_BUNDLE_URL is not set.\n"
            "\n"
            "A product build needs the recompiled game C, and this repository does\n"
            "not carry it: generated/ is a recompilation of the game, and\n"
            "psxrecomp/tools/package_setup_host.sh strips it from every release.\n"
            "\n"
            "Option A - let CI do it (recommended): point the repository secret at a\n"
            "  bundle you packed yourself:\n"
            "    python3 psxrecomp/psxrecomp_cli.py generate --config game.toml \\\n"
            "        --project-root . --disc '<your Wild 9 .cue>'\n"
            "    scripts/pack_generated_bundle.py\n"
            "    # upload generated-bundle.tar.gz somewhere, set the secret to its URL\n"
            "\n"
            "Option B - no secret needed: generate locally first, and the fetch step\n"
            "  will see the marker and move on.\n"
            "\n"
            "If the URL points at a private repository, also set\n"
            "PSXRECOMP_BUNDLE_TOKEN to a token with read access to it. A private host\n"
            "answers 404 to an unauthenticated request, which looks exactly like a\n"
            "wrong URL -- hence the two settings together rather than one.",
            file=sys.stderr,
        )
        return 2

    print("  fetching the generated/ bundle from PSXRECOMP_GENERATED_BUNDLE_URL")
    token = os.environ.get("PSXRECOMP_BUNDLE_TOKEN", "").strip() or None
    if token:
        print("  authenticating with PSXRECOMP_BUNDLE_TOKEN")
    with tempfile.TemporaryDirectory(prefix="wild9bundle") as tmpname:
        tmp = pathlib.Path(tmpname)
        archive = tmp / "bundle.tar.gz"
        try:
            download(url, archive, token)
        except urllib.error.HTTPError as exc:
            if exc.code in (401, 403, 404):
                print(
                    f"  FAIL: the host refused the request (HTTP {exc.code}).\n"
                    "        For a private repository this is what a wrong, expired or\n"
                    "        under-scoped token looks like -- and it is indistinguishable\n"
                    "        from a wrong URL. Check both:\n"
                    "          - the token has read access to the bundle's repository\n"
                    "          - PSXRECOMP_GENERATED_BUNDLE_URL points at the file, not the\n"
                    "            repository's HTML page",
                    file=sys.stderr,
                )
                return 1
            fail(f"download failed: HTTP {exc.code} {exc.reason}")
            return 1
        except urllib.error.URLError as exc:
            fail(f"download failed: {exc.reason}")
            return 1
        except ValueError as exc:
            fail(f"download failed: {exc}")
            return 1

        print(f"  downloaded {archive.stat().st_size / 1e6:.1f} MB")
        with tarfile.open(archive, "r:gz") as tar:
            try:
                member = tar.extractfile(MANIFEST_NAME)
            except KeyError:
                fail(f"the archive has no {MANIFEST_NAME}")
                return 1
            if member is None:
                fail(f"the archive has no {MANIFEST_NAME}")
                return 1
            try:
                manifest = json.loads(member.read())
            except json.JSONDecodeError as exc:
                fail(f"the manifest is not valid JSON: {exc}")
                return 1

        staging = verify(manifest, root, tmp, archive)
        if staging is None:
            return 1

        if generated.exists():
            shutil.rmtree(generated)
        shutil.copytree(staging / "generated", generated)

    print(f"  {GEN_MARKER} is in place")
    return 0


if __name__ == "__main__":
    sys.exit(main())
